swagger: "2.0"
info:
  version: "0.0.1"
  title: Coglite App
# during dev, should point to your local machine
host: localhost:3500
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /v1/user/auth/:
    # binds a127 app logic to a route
    x-swagger-router-controller: Users
    post:
      description: User tokens for google api permissions
      # used as the method name of the controller
      operationId: token
      parameters:
        - name: uid
          in: formData
          description: The user firebase id
          required: true
          type: string
        - name: displayName
          in: formData
          description: The user Name and Surname
          required: true
          type: string
        - name: photoURL
          in: formData
          description: The user photo url
          required: true
          type: string
        - name: email
          in: formData
          description: The user email address
          required: true
          type: string
        - name: accessToken
          in: formData
          description: The user accessToken
          required: true
          type: string
        - name: refreshToken
          in: formData
          description: The user refreshToken
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /v1/user/group/create:
    post:
      description: User tokens for google api permissions
      # used as the method name of the controller
      parameters:
        - name: ownerId
          in: formData
          description: group owner id
          required: true
          type: string
        - name: name
          in: formData
          description: group name
          required: true
          type: string
        - name: description
          in: formData
          description: group description
          required: false
          type: string
        - name: members
          in: formData
          description: group participents
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"          
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
